// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmY1PJZhdkzJhU-1CZ2QczHmAoUiCGFGc',
    appId: '1:611774492421:web:edf2c987480a2a9217d16c',
    messagingSenderId: '611774492421',
    projectId: 'foodbillingapp',
    authDomain: 'foodbillingapp.firebaseapp.com',
    databaseURL: 'https://foodbillingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodbillingapp.firebasestorage.app',
    measurementId: 'G-P8ZCJ1EDZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB2S04CuG4sNEp00Y3MuGnKBCSQosCEn4',
    appId: '1:611774492421:android:e3e9708d97f3f43117d16c',
    messagingSenderId: '611774492421',
    projectId: 'foodbillingapp',
    databaseURL: 'https://foodbillingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodbillingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFd2tme5g6jYLzOChPiPohDb8YY881-vI',
    appId: '1:611774492421:ios:27a8997bc531df3d17d16c',
    messagingSenderId: '611774492421',
    projectId: 'foodbillingapp',
    databaseURL: 'https://foodbillingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodbillingapp.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFd2tme5g6jYLzOChPiPohDb8YY881-vI',
    appId: '1:611774492421:ios:27a8997bc531df3d17d16c',
    messagingSenderId: '611774492421',
    projectId: 'foodbillingapp',
    databaseURL: 'https://foodbillingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodbillingapp.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmY1PJZhdkzJhU-1CZ2QczHmAoUiCGFGc',
    appId: '1:611774492421:web:5e164c5031ca827c17d16c',
    messagingSenderId: '611774492421',
    projectId: 'foodbillingapp',
    authDomain: 'foodbillingapp.firebaseapp.com',
    databaseURL: 'https://foodbillingapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'foodbillingapp.firebasestorage.app',
    measurementId: 'G-D03TCWF88D',
  );
}
